
version: '3' # Version de Docker Compose à utiliser

services:
  app: # Nom du premier service
    image: nom_de_l_image # Image Docker utilisée pour ce service
    ports:
      - "port_hôte:port_conteneur" # Mappage des ports
    environment:
      - VARIABLE_1=valeur_1 # Variables d'environnement
    volumes:
      - /chemin/hote:/chemin/conteneur # Mappage de volumes
    depends_on:
      - service2 # Dépendances entre les services

 

networks:
  mynetwork: # Définition d'un réseau personnalisé
    driver: bridge # Type de réseau